// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0s3LcL7qBjT10py0XnLxVcJfN_WWlGn4',
    appId: '1:507892246638:android:5d848c8ed587f19970de7f',
    messagingSenderId: '507892246638',
    projectId: 'carecircle-app',
    storageBucket: 'carecircle-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCr7PAC91M-dee3S4abP-5HLzsfjVvj0-Q',
    appId: '1:507892246638:ios:8447c3e2a01bc94c70de7f',
    messagingSenderId: '507892246638',
    projectId: 'carecircle-app',
    storageBucket: 'carecircle-app.firebasestorage.app',
    androidClientId: '507892246638-3cu3f5lt9abkmld72s8j8fc52rpkepsu.apps.googleusercontent.com',
    iosClientId: '507892246638-74ba38ud07jash9tnhh18inu3p3gjgjn.apps.googleusercontent.com',
    iosBundleId: 'com.example.background',
  );
}
